### ISSUE TITLE
JWT Token...

### ISSUE THREAD

**Issue by jonathangerbaud** [supabase/storage#295]
Alright, your landing page states "Build in a weekend", but I feel like I've spent the weekend already trying to make one of the simplest basic features work, and guess what? Still not working!

So, what am I talking about?

Freaking progress event on uploading files. There's an issue that's been open for ages, namely [https://github.com/supabase/storage-api/issues/23](https://github.com/supabase/storage-api/issues/23)

Almost two years! One would think that such a basic feature would be supported by such a big tool as Supabase, but no.

So instead of making me save time coding, you actually make me waste time. 

I even went through your code to try to make this thing working. But enough complaining. I figured that I might as well open an issue, since you know your tool better than me, and I'm quite tired of fighting right now. 

So what's the problem? I need progress event on file uploads.

Solution? Although, clearly far from ideal, found in the old issue linked above.

The thing is that it's working... unless you have a policy on your bucket stating that only the authenticated user can upload a file.

One thing I've noticed is that when I use your js library, the authentication token is not the same as the one provided by `supabase.auth.headers`.

So you're using JWT tokens it seems. No idea how it works, nor do I wanna know. I just want to know how you generate this token, or better how I can retrieve it, so that I can put it my header for my XMLHTTPRequest.

Of course, better solution would be that your api provides callbacks.

Something like:

````
supabase.storage
.from("my_bucket')
.upload("my_file.jpg", myFile, {
   upsert: true,
   onStart: () => console.log("onStart"),
   onProgress: (progress) => console.log("onProgress " + progress),
   onComplete: () => console.log("onComplete")
})
```

**Comment by inian** [comment]
Hi, there is a minimal example [here](https://github.com/supabase/supabase/tree/master/examples/storage/resumable-upload-uppy) for uploading assets to storage and listening to progress events via our new [resumable uploads feature](https://supabase.com/docs/guides/storage/uploads#resumable-upload). 

Am closing this issue, but do let us know if you run into any issues or if there are any ways to improve the DX.
