### ISSUE TITLE
The supabase storage api does not parse the RANGE http header

### ISSUE THREAD

**Issue by Ji-Xinyou** [supabase/storage#322]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Supabase supports RESTful API to access its storage.

For upper layer applications, which require range read for inner bytes, they typically attach a RANGE header in the GET request for the object in supabase storage.

However, currently the supabase storage API does not parse the RANGE header, working as if the RANGE header is not attached.

We found out that although [this](https://github.com/supabase/storage-api/blob/1794d04ab0e7259d9058293e257f442015252ec3/src/storage/renderer/asset.ts#L14-L20) uses the RANGE header, but the inside of it does not.
```ts
getAsset(request: FastifyRequest, options: RenderOptions) {
    return this.backend.getObject(options.bucket, options.key, options.version, {
      ifModifiedSince: request.headers['if-modified-since'],
      ifNoneMatch: request.headers['if-none-match'],
      range: request.headers.range,
    })
  }
```

```ts
  async getObject(
    bucketName: string,
    key: string,
    version: string | undefined
  ): Promise<ObjectResponse> {
    const file = path.resolve(this.filePath, withOptionalVersion(`${bucketName}/${key}`, version))
    const body = fs.createReadStream(file)
    const data = await fs.stat(file)
    const { cacheControl, contentType } = await this.getFileMetadata(file)
    const lastModified = new Date(0)
    lastModified.setUTCMilliseconds(data.mtimeMs)

    const checksum = await fileChecksum(file)

    return {
      metadata: {
        cacheControl: cacheControl || 'no-cache',
        mimetype: contentType || 'application/octet-stream',
        lastModified: lastModified,
        // contentRange: data.ContentRange, @todo: support range requests
        httpStatusCode: 200,
        size: data.size,
        eTag: checksum,
        contentLength: data.size,
      },
      body,
    }
  }
```

## To Reproduce

Previous discussion on this issue is [here](https://github.com/apache/incubator-opendal/issues/2199).

To reproduce this, you can simply read an object from supabase with RANGE header, and the RANGE header will not work as expected.

## Expected behavior

The supabase storage API should parse the RANGE header and hence support range read.

**Comment by Xuanwo** [comment]
More specifically, Supabase Storage SaaS does not support range reading (I don't know what's the underlying storage service underhood).

**Comment by fenos** [comment]
I believe that the range header is not supported on the File System Storage just yet. The S3 Backend adapter should support it

Open for contributions on this

**Comment by fenos** [comment]
This is now fixed by https://github.com/supabase/storage/pull/358
