### ISSUE TITLE
gitpkg.now.sh error

### ISSUE THREAD

**Issue by zuohuadong** [supabase/storage#325]
# Bug report
”gitpkg.now.sh“ is not accessible in China, can I customize the address?

## Screenshots

![image](https://user-images.githubusercontent.com/11203929/236210075-2e25ea15-f5a2-4711-8334-477dcd455fcb.png)

## System information

- OS:  Alamlinux9
- Version of supabase-js: 6.0.2
- Version of Node.js: 18.10

**Comment by fenos** [comment]
Unfortunately, it will take a bit longer to have the package supported on mainstream npm.
No eta just yet, but i'll be updating this issue once that's done.

Closing for now
