### ISSUE TITLE
uploader: `invalid_mime_type` responds with 422 instead of 415

### ISSUE THREAD

**Issue by imageck** [supabase/storage#329]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On failing MIME type validation, `upload` throws a `StorageBackendError` with status code set to 422.

## Additional context

A more suitable status code might be 415, as per [RFC9110](https://httpwg.org/specs/rfc9110.html#status.415).

**Comment by fenos** [comment]
@imageck thanks for this, we'll amend the status code!

**Comment by fenos** [comment]
This is now being fixed
