### ISSUE TITLE
>100 KB File Upload Throws "TypeError: fetch failed"

### ISSUE THREAD

**Issue by VCasecnikovs** [supabase/storage#368]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When trying to upload big file from server-side user action in Next.JS it throws an error described above.

In 10% if the image is less then 100KB all is done successfully.

Code to throw an error
```
 const { data, error } = await createServerActionClient({ cookies }, { supabaseKey: process.env.SUPABASE_SERVICE_ROLE_KEY, supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL })
            .storage
            .from('images')
            .upload(path, image);
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Mac OS
2. Call function above from Next.JS server actions (I saw same problem on StackOverflow without Next.JS server actions)
3. Error

## Expected behavior

The image must be uploaded to the Storage

## Screenshots
![Screenshot 2023-09-17 at 20 53 42](https://github.com/supabase/storage-api/assets/29467201/47050150-edef-4c22-a919-cfd882fd0bbe)

## System information

- OS: MacOS
- Version of supabase-js: 2.33.2
- Version of Node.js: 20.5.1

## Additional context
Error, which looked similar (NOT ON GITHUB):
https://stackoverflow.com/questions/76424910/supabase-typeerror-fetch-failed

**Comment by VCasecnikovs** [comment]
I have temporary solved this problem for myself:

The problem happens, when I send File to Supabase Storage.

To solve the problem, I send Array Buffer:
```
let array_buffer = await image.arrayBuffer();
```

**Comment by arthur-es** [comment]
I'm having this issue aswell.
![image](https://github.com/supabase/storage/assets/37699234/41b0ec6c-d10b-4766-86a3-0423cf59d7ac)

**Comment by simonhackler** [comment]
I have to send array buffers as well.

**Comment by fenos** [comment]
Closing this issue for now. By sending arrayBuffer seems the correct approach.
