### ISSUE TITLE
Can't upload files to storage

### ISSUE THREAD

**Issue by aldaprojects** [supabase/storage#413]
## Describe the bug

It's simple. I can't upload files to any bucket. I just create a new bucket, try to upload a file and i get an Internal Server Error.

## To Reproduce

1. Go to storage
2. Create a new bucket
3. Upload a file (drop or select)
![image](https://github.com/supabase/supabase/assets/57024621/e8fffe21-2384-49cb-a959-19b65b363392)

## Expected behavior

To upload a file correctly.

## Screenshots

![image](https://github.com/supabase/supabase/assets/57024621/2d4f4344-57a9-4696-aadc-26d849ebdbd4)

## Additional context

I created a new project and it was available to upload a file.

**Comment by fenos** [comment]
@aldaprojects are you self-hosting Storage or are you using the managed version?

If you are using the managed version could you please reach out to the support team, I'll be glad to look into this issue myself.

If you are self-hosting could you please share more information on how you are setting up storage?

**Comment by aldaprojects** [comment]
> @aldaprojects are you self-hosting Storage or are you using the managed version?
> 
> If you are using the managed version could you please reach out to the support team, I'll be glad to look into this issue myself.
> 
> If you are self-hosting could you please share more information on how you are setting up storage?

I'm using the managed version. I already reached out to the them and got the ticket id 2251094845

**Comment by fenos** [comment]
hello @aldaprojects I've received the ticket and answered.
The issue you are experiencing is unrelated to Storage code base.

Closing the issue. Happy to follow up on the ticket
