### ISSUE TITLE
File upload is not possible when using custom roles

### ISSUE THREAD

**Issue by harukaxq** [supabase/storage#414]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
I created a custom role using **create custom_role;**, but cannot upload the file.

## To Reproduce

1. clone the following repository
https://github.com/harukaxq/role_test

2. supabase start 
3. create a file in front-example/.env.local
NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM 4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
4. yarn dev in front-example
5. open http://localhost:3000/login and do a signup
6. update role to staff
update "auth"." users" set role='staff';. 
7. open http://localhost:3000/login and login
8. open http://localhost:3000 and upload an image
9. an error is displayed
<img width="1534" alt="SCR-20240110-qius" src="https://github.com/supabase/storage/assets/33682662/4c5d80ef-7131-41d3-9d04-ffb45edbac27">
<img width="1374" alt="SCR-20240110-qktk" src="https://github.com/supabase/storage/assets/33682662/433bcadd-68e2-435d-8c72-936ab5f8abe3">

The above is reproduced in the local environment, but the same error occurs on supabase.com.

## Expected behavior

Uploading is normal even after switching to staff role.

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of supabase-js: 2.38.1
- Version of Node.js: v18.15.0

## Additional context

Similar problems occur in flutterflow.
I read the following issue and ran "grant staff to authenticator;grant anon to custom_role;" but that didn't solve the problem
https://github.com/supabase/storage/issues/369

**Comment by fenos** [comment]
Related to #369 

You'll need to grant the following permissions to your custom role:

```
grant custom_role to authenticator;
grant anon to custom_role;
```
