### ISSUE TITLE
`move`, `copy` do not returning new file id

### ISSUE THREAD

**Issue by bombillazo** [supabase/storage#438]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When we use the `move` endpoint, we do not get the new id of the file.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a file
2. Use the `object/move` endpoint to move a file
3. response is only `{ message: "Successfully moved" }`

## Expected behavior

We expect to get the new file id so we can match the file internally to our relations.

## System information

- Version of supabase-js: 2.39.3
- Storage version: v0.48.1

**Comment by bombillazo** [comment]
This would not be needed if #359 is fixed

**Comment by fenos** [comment]
This is now fixed, move will not create a new id. However, the copy command will still need to create a new object since it is a brand new object

**Comment by fenos** [comment]
Also added support for returning the ID on move / copy operation on this PR #444 
Note: keep in mind that this fix is not yet release to the Hosted version of Supabase, will be released soon next week

**Comment by fenos** [comment]
This is now being supported
