### ISSUE TITLE
Add `file_metadata` field to objects schema

### ISSUE THREAD

**Issue by bombillazo** [supabase/storage#439]
# Feature Request

Currently, the `objects` schema in the Storage API schema is a light abstraction over the S3 storage. There is a metadata column in the `objects` table, but it corresponds to the metadata of the S3 file and cannot be used by the user.  The API does not expose any way to add related metadata to a file to the objects directly. This metadata would ideally be in JSON format to contain user-determined data. Currently, the user needs to get around this limitation by either:

- Create another table that relates this metadata to the `storage.objects` table. This dramatically complicates querying, migrations, and client usage for something that could be colocated within the same table.
- Directly modify the `storage` schema to add this new functionality, potentially breaking compatibility with Supabase-controlled services and implementation.

The storage API should natively support metadata, and the API / JS clients should be updated to enable this powerful and common feature for file storage management. My proposal is to add a new column called `file_metadata` to differentiate it to the current `metadata` field.

**Comment by fenos** [comment]
@bombillazo I generally agree that allowing Storing arbritary metadata could be a nice feature to have in Storage.
Will add this on the roadmap! 🎉

**Comment by logemann** [comment]
strong agree on adding custom metadata per storge object. Having to maintain a mirror table just for additional data is a pain, especially the lack of usable triggers to keeping both sides in sync.

**Comment by dmbr0** [comment]
+2 for this. I would definitely like this. would like to tag files that are being uploaded.

**Comment by Razikus** [comment]
+1

**Comment by zhanziyang** [comment]
+1 for this

**Comment by joe-ashwell** [comment]
Also +1

**Comment by lecramr** [comment]
+1

**Comment by danvoyce** [comment]
+1000000000

I'm currently having to add metadata into my file names, so would love to clean up this mess!

**Comment by momongah** [comment]
+1 for this. I'm currently working with AI generated images and need to store the prediction parameters that generated each image.

**Comment by KindArt** [comment]
+1

**Comment by ykoitzsch** [comment]
+1 looking forward to this

**Comment by vatanak10** [comment]
+1

**Comment by loringabriel** [comment]
+1

**Comment by PremchandGat** [comment]
+1 looking for same

**Comment by normanyu** [comment]
This would improve my workflow with supabase as well. Right now, I need to keep a separate table and keep it in sync every time i upload, move or delete objects.

**Comment by Gbillington1** [comment]
+1

I switched from self hosting to supabase, closed down my own s3 bucket to use supabase storage, and now I can't store metadata on the objects... Please please please add this functionality!

**Comment by Protonosgit** [comment]
+1 seems very helpful!!

**Comment by patra0o** [comment]
+1

**Comment by fahad-frontend** [comment]
+999 would really help out majorly in making supabase storage my go to for all apps. Currently having to use alternatives despite using supabase db and auth

**Comment by tusamni** [comment]
Great request.

**Comment by bombillazo** [comment]
@fenos on this topic, since we're not sure when we might get this, is it wise to add a custom trigger to the `storage` schema so that when a DELETE event happens on the objects table, we can automatically delete it in our metadata table?

These are the type of things having a dedicated file_metadata field would prevent so we wouldn't have to sync data and resources across tables.

**Comment by Aadilhassan** [comment]
+1

**Comment by Toshiro00** [comment]
+1 it could prevent extra table for metadata

**Comment by Aadilhassan** [comment]
@fenos 
Thank you for your work on this project. Could you please provide an example implementation for this feature? It would be really helpful for understanding how to integrate it properly.

**Comment by tusamni** [comment]
Thanks for the update @fenos. I'm currently building my photography portfolio. I'm assuming I'd be able to store photo JSON data alongside each image uploaded to storage, correct?

If so, I'm a customer now!

**Comment by bombillazo** [comment]
Hey @fenos , I also dont see any way to pass the new `user_metadata` field to the POST/PUT Storage API endpoints.

**Comment by fenos** [comment]
@tusamni Yes correct! 🎉 

@bombillazo The client-side changes are in the making

**Comment by felipenmoura** [comment]
Hey there.
So...any update or documentation on this? I saw a merged PR but I couldn't find a way to have it working.
Should I go ahead and create a table and all that it implies to deal with extra data for media?

Thanks.

**Comment by logemann** [comment]
Yeah... any news on it would be nice.

**Comment by y4my4my4m** [comment]
@felipenmoura @logemann 
https://github.com/supabase/storage-js/pull/207 
this needs to be merged before you can use it with the client

**Comment by felipenmoura** [comment]
> @felipenmoura @logemann [supabase/storage-js#207](https://github.com/supabase/storage-js/pull/207) this needs to be merged before you can use it with the client

Awesome, sounds great

Thanks.

**Comment by tHyenigmatiC** [comment]
+1 Waiting for this.

**Comment by valentindoering** [comment]
+1 waiting for this

**Comment by craig-at-metashield-io** [comment]
++ excited for this!

**Comment by anthonylan** [comment]
+1 waiting for this feature

**Comment by naimRahman08** [comment]
+1 waiting for this

**Comment by tillka** [comment]
I am confused. I followed the merge-chain and this feature seems to be fully merged and released. I updated my @supabase/supabase-js package so that it includes @supabase/storage-js:2.7.0. However the type FileOptions do not include a metadata field 

```ts
export interface FileOptions {
  /**
   * The number of seconds the asset is cached in the browser and in the Supabase CDN. This is set in the `Cache-Control: max-age=<seconds>` header. Defaults to 3600 seconds.
   */
  cacheControl?: string
  /**
   * the `Content-Type` header value. Should be specified if using a `fileBody` that is neither `Blob` nor `File` nor `FormData`, otherwise will default to `text/plain;charset=UTF-8`.
   */
  contentType?: string
  /**
   * When upsert is set to true, the file is overwritten if it exists. When set to false, an error is thrown if the object already exists. Defaults to false.
   */
  upsert?: boolean
  /**
   * The duplex option is a string parameter that enables or disables duplex streaming, allowing for both reading and writing data in the same stream. It can be passed as an option to the fetch() method.
   */
  duplex?: string
}
```

Similarly, neither .info() nor .exists() exist on `supabase.storage.fom(bucket)`.

Could you update the documentation or bring me on the right track @fenos ?

**Comment by fenos** [comment]
@tillka you should be updating storage-js to @supabase/storage-js:2.7.1

**Comment by pi43r** [comment]
Do I get this right that metadata does not yet work with supabase.storage? I have to use the dedicated StorageClient?

I would like to get my stored metadata through supabase.storage.list() rather than iterating over it and calling storageClient.info() for each file.

**Comment by traianturcu** [comment]
It would be really nice if `supabase.storage.list()` would return `user_metadata` along with the other file properties! We use the custom metadata field to store the original file names..

In the meantime the solution I'm using is to send a request to the backend where I query the `storage.objects` table directly:

```
    const { data, error } = await supabase
      .schema("storage")
      .from("objects")
      .select("*")
      .eq("bucket_id", bucketId)
      .eq("owner_id", userId)
      .ilike("user_metadata->>originalFileName", `%${search}%`);
```

**Comment by jdhenry08** [comment]
> It would be really nice if `supabase.storage.list()` would return `user_metadata` along with the other file properties! We use the custom metadata field to store the original file names..
> 
> In the meantime the solution I'm using is to send a request to the backend where I query the `storage.objects` table directly:
> 
> ```
>     const { data, error } = await supabase
>       .schema("storage")
>       .from("objects")
>       .select("*")
>       .eq("bucket_id", bucketId)
>       .eq("owner_id", userId)
>       .ilike("user_metadata->>originalFileName", `%${search}%`);
> ```

How are you doing this? I keep getting an error: 
```
{
  code: 'PGRST106',
  details: null,
  hint: null,
  message: 'The schema must be one of the following: pg_pgrst_no_exposed_schemas'
}
```

**Comment by traianturcu** [comment]
You need to expose the storage schema from Settings > API > Exposed Schemas

**Comment by nicolas-geysse** [comment]
+1 waiting for this feature

**Comment by devsrealm** [comment]
@fenos Is there a way to update the file user_metadata? I can't find that.

**Comment by elyobo** [comment]
Do we need to open a new feature request to add the user metadata to `supabase.storage.list()`? Having to make `n` additional requests to `.info()` to get the metadata seems excessive, especially when the desired data is already available on the storage rows being retrieved.
