### ISSUE TITLE
Private bucket files become public

### ISSUE THREAD

**Issue by Torwent** [supabase/storage#446]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Accessing a file in a private bucket via the endpoint makes it available publicly for anyone.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. On the dashboard go to storage
2. Create a private bucket, I'll call it "test"
3. Upload a file to the bucket, for this example I'll call it "test.txt"
4. Go to the policies and create a policy for selecting files on the bucket with the following rule and save it:
```
((bucket_id = 'test'::text) AND (auth.role() = 'authenticated'::text))
```
5. With a REST client, visit the following URL: `https://project_id.supabase.co/storage/v1/object/authenticated/test/test.txt` with the project api key and authorization token in the headers as explained in the documentation: https://supabase.github.io/storage/#/object/get_object_authenticated__bucketName___wildcard_
6. Once you accessed the file you can now visit the URL `https://project_id.supabase.co/storage/v1/object/public/test/test.txt` without any authentication whatsoever.

## Expected behavior

On step 6 above, the file should never be accessed unless you are authenticated.

## System information

- OS: Windows, Android
- Browser: Brave, Chrome, Brave mobile, Chrome mobile

## Additional context

I may just not be understanding that this is supposed to work this way, but doesn't look like it should.

**Comment by fenos** [comment]
Hello @Torwent Thanks a lot for reporting this issue!

After an investigation, I found out that this was happening under a certain edge case in our edge function that instructs the CDN.

I've promptly fixed the edge case and cleared the cache for the affected assets.
In your case you should now receive a 400 error Bucket not found on the `public` URL.

Again, thanks for reporting this issue.

**Comment by Torwent** [comment]
I'll give it a go tomorrow! Yeah I figured it was some caching issue after some debugging with @GaryAustin1 
Thank you the quick fix and keep up the awesome work!
