### ISSUE TITLE
S3 Upload with presigned URL

### ISSUE THREAD

**Issue by trevorpfiz** [supabase/storage#465]
# Improve documentation

## Link 

https://supabase.com/docs/guides/storage/uploads/s3-uploads

## Describe the problem

I am looking for a way to use presigned URLs with the new S3 Uploads. I am following the AWS S3 Image Upload template from Vercel https://github.com/vercel/examples/tree/main/solutions/aws-s3-image-upload

## Describe the improvement

A section added to the docs that shows how to use presigned URLs for S3 Uploads.

## Additional context

https://discord.com/channels/839993398554656828/1236819104376164402

**Comment by fenos** [comment]
Hello, @trevorpfiz this is not currently supported at the moment, but it will be in the near future

**Comment by bombillazo** [comment]
Does this also affect pre-signed URLs to download files directly from S3? We're using the S3 compatible buckets with teh AWS creds to create AWS S3 signed URLs but we get this error:

<img width="508" alt="image" src="https://github.com/supabase/storage/assets/44002321/e02a7f4d-ba40-46a5-baf8-761ce65b3772">

**Comment by fenos** [comment]
Yes, pre-signed URL is a feature that will be coming soon

**Comment by bombillazo** [comment]
This is awesome news, cant wait to try it out!

**Comment by bombillazo** [comment]
How can we upgrade to v1.5.1?

**Comment by Sangeeth-versos** [comment]
I am trying to create pre-signed url for file download and still getting 

<img width="403" alt="Image" src="https://github.com/user-attachments/assets/ac2c65ce-8629-46e0-955c-8c493c2614b3" />
