### ISSUE TITLE
upload file failed in studio when i use minio as storage backend

### ISSUE THREAD

**Issue by unfazed2049** [supabase/storage#523]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am using MinIO as the backend storage service for S3, and I have correctly configured the environment variables such as STORAGE_BACKEND, STORAGE_S3_ENDPOINT, S3_PROTOCOL_ACCESS_KEY_ID, and S3_PROTOCOL_ACCESS_KEY_SECRET. However, when I attempt to upload a file on Studio, an exceptional error occurs.

```
url: 
method: post
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Open Page 'studio'
2. Click on 'storage'
3. Click on 'Upload files'

## Expected behavior

Normal file upload.

## Screenshots
![Buckets-Supabase](https://github.com/user-attachments/assets/88c8795f-689d-479c-8516-6543fbb25064)
![Desktop-screenshot](https://github.com/user-attachments/assets/b10e414e-3cca-4083-9022-4025cc5516b9)
![Desktop-screenshot (1)](https://github.com/user-attachments/assets/3bc48597-61bb-4ac5-a9ea-e3c5866a96c5)

## System information

- OS: [e.g. macOS]
- Browser (if applies) [e.g. chrome]
- Version of supabase-storage: [e.g. 1.7.1]
- Version of Node.js: [e.g. 18.17.1]

**Comment by unfazed2049** [comment]
i am sorry, i miss the error infomation. 
```
url: http://localhost:8000/storage/v1/object/test/archive.png
method: POST
{
    "statusCode": "500",
    "code": "S3Error",
    "error": "Could not load credentials from any providers",
    "message": "CredentialsProviderError"
}

```

**Comment by fenos** [comment]
Hi @unfazed2049 

The environment variables that you need to set are:

```
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
```

These will grant permission to your Minio server.


To clarify, these credentials prefixed with `S3_PROTOCOL` are controlling Storage's own S3 protocol.
In this case the below envs, will set specific credentials for the client to use via the S3 protocol.

```
S3_PROTOCOL_ACCESS_KEY_ID
S3_PROTOCOL_ACCESS_KEY_SECRET
```

**Comment by fenos** [comment]
If you need any more help just drop a message, but I'm pretty sure that setting the right envs will fix the issue.

**Comment by unfazed2049** [comment]
> Hi @unfazed2049
> 
> The environment variables that you need to set are:
> 
> ```
> AWS_ACCESS_KEY_ID=
> AWS_SECRET_ACCESS_KEY=
> ```
> 
> These will grant permission to your Minio server. You can take a look here: https://github.com/supabase/storage/blob/master/docker-compose.yml#L28-L34
> 
> To clarify, these credentials prefixed with `S3_PROTOCOL` are controlling Storage's own S3 protocol. In this case the below envs, will set specific credentials for the client to use via the S3 protocol.
> 
> ```
> S3_PROTOCOL_ACCESS_KEY_ID
> S3_PROTOCOL_ACCESS_KEY_SECRET
> ```

Thanks for your reply! i didn't know aws-sdk read then env variable, so i make a mistake. BTW, Hope you have a great time!
