### ISSUE TITLE
Delayed Object Availability in Supabase Storage After Insert Trigger

### ISSUE THREAD

**Issue by SimoneBersani** [supabase/storage#535]
# Delayed Object Availability in Supabase Storage After Insert Trigger & Duplicate API Calls

## Describe the Bug

When uploading a new file to Supabase Storage, a trigger is set to call an API to generate embeddings for an AI assistant. However, the trigger seems to be firing before the file is fully available, causing an "Object not found" error unless a timeout is added. Additionally, the trigger/API call is being executed twice for a single upload event.

## To Reproduce

1. Create a trigger in the database to execute after an insert on the `storage.objects` table, which calls a function to notify an API of the new file.
2. Upload a new file to the Supabase Storage bucket.
3. Observe two issues:
   - The API call sometimes fails with an "Object not found" error.
   - The API call is executed twice for a single upload event.

Code snippets for better understanding:

### SQL Trigger Code
```sql
CREATE OR REPLACE FUNCTION public.notify_new_file()
RETURNS trigger AS $$
DECLARE
  retval json;
  API_ENDPOINT text := 'http://172.17.0.1:11000/api/embedDocument';
  API_KEY text;
BEGIN
  SELECT '...anon_key...' INTO API_KEY;
  
  BEGIN
    SELECT 
        * INTO retval
    FROM 
        http((
        'POST',
        API_ENDPOINT,
        ARRAY[http_header ('Authorization', 
                'Bearer ' || API_KEY)],
        'application/json',
        json_build_object('id', NEW.id, 'bucket_id', NEW.bucket_id, 'name', NEW.name)::text
        ));
  EXCEPTION
    WHEN OTHERS THEN
      RAISE EXCEPTION 'Error occurred while calling API: %', SQLERRM;
  END;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_insert_storage_objects
AFTER INSERT ON storage.objects
FOR EACH ROW
EXECUTE FUNCTION notify_new_file();
```

### Backend Code
```javascript
// Failing backend code
const { data: document, error: documentSelectError } =
    await supabaseClient.storage.from("filemanager").download(name);

if (documentSelectError) {
    throw new Error("Document not found");
}
const doc = document;
console.log("DOC: ", doc);
```

```javascript
// Working backend code with setTimeout
setTimeout(async () => {
    const { data: document, error: documentSelectError } =
        await supabaseClient.storage.from("filemanager").download(name);

    if (documentSelectError) {
        throw new Error("Document not found");
    }
    const doc = document;
    console.log("DOC: ", doc);
}, 1000);
```

## Expected Behavior

The API should be called once after a new file is successfully uploaded and fully available, without the need for a timeout. The backend should not encounter an "Object not found" error.

## Screenshots

Not applicable, but console logs can be provided if necessary.

## System Information

- OS: macOS and Linux (both tested)
- Browser: Chrome (both tested)
- Version of supabase: 1.183.5
- Version of Node.js: 20.12.2

## Additional Context

- The backend API call works as expected when a timeout is added, suggesting there's a delay in the file's availability after it's logged in the `storage.objects` table.
- The duplicate API calls issue suggests that the trigger might be firing more than once for a single event.

---

Thank you for addressing these issues. Looking forward to your assistance.

**Comment by SimoneBersani** [comment]
## Update

It looks like the row on storage.objects is being inserted one time, then deleted and then re-inserted with a different ID. But in both cases I need to put the setTimeout to download the object correctly.

**Comment by fenos** [comment]
Hi @SimoneBersani 

Yes, this behaviour is expected.
The reason behind this is that Storage actually tries to insert the row before beginning to accept the upload, that is to check RLS.

If RLS passes it rolls back the record and the upload begins.
Once the upload completed, the record is then persisted. 

One way to get around this for now, is to run the trigger only if the `metadata` is NOT NULL.
This way, you can safely assume you are in the final transaction.

However, my plan is to add a helper function such as `storage.isRlsCheck()` that you use in the trigger and simply do nothing or add yourown checks

**Comment by SimoneBersani** [comment]
Thanks @fenos for the help. I'll try your solution.

**Comment by SimoneBersani** [comment]
That seemed to resolve the issue. Thanks for the support!
