### ISSUE TITLE
Resumable uploads error

### ISSUE THREAD

**Issue by shayktech** [supabase/storage#554]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Using this documentation: https://supabase.com/docs/guides/storage/uploads/resumable-uploads and this endpoint url: http://localhost:54321/storage/v1/s3/upload/resumable, the upload fails with the following error:
```
{
"raw": "{}",
"name": "TypeError",
"message": "Cannot read properties of undefined (reading 'tagName')",
"stack": "TypeError: Cannot read properties of undefined (reading 'tagName')\n at OrderedObjParser.parseXml (/app/node_modules/fast-xml-parser/src/xmlparser/OrderedObjParser.js:283:29)\n at XMLParser.parse (/app/node_modules/fast-xml-parser/src/xmlparser/XMLParser.js:35:48)\n at handleParseXml (/app/node_modules/fastify-xml-body-parser/index.js:48:38)\n at IncomingMessage.endListener (/app/node_modules/fastify-xml-body-parser/index.js:40:17)\n at IncomingMessage.emit (node:events:519:28)\n at endReadableNT (node:internal/streams/readable:1696:12)\n at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
}
```

## To Reproduce

Set up a local environment [the usual way](https://supabase.com/docs/guides/cli/local-development) and try to upload a file with resumable upload as documented here: https://supabase.com/docs/guides/storage/uploads/resumable-uploads.

## Expected behavior

File is uploaded to the specified location.

## Screenshots

n/a

## System information

- OS: macOS
- Browser: chrome
- Version of supabase-js: 2.45.0
- Version of Node.js: 22.5.1

## Additional context

n/a

**Comment by fenos** [comment]
Hello @shayktech the URL your are using is incorrect, you should not prefix it with `/s3` that is another protocol

the correct URL is:
```
http://localhost:54321/storage/v1/upload/resumable,
```
