### ISSUE TITLE
"API error happened while trying to communicate with the server" when trying to access a bucket in local studio

### ISSUE THREAD

**Issue by Wizzel1** [supabase/storage#582]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am not able to view the contents of my buckets when developing locally

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install the latest supabase cli version.
2. Run `supabase start`
3. Create a bucket
4. Try to access the bucket 

## Screenshots
![Unbenannt](https://github.com/user-attachments/assets/68756fa0-1837-4f4e-8920-7fdb97ef2f30)

## System information

- OS: Windows
- Browser (if applies)  chrome
- Version of supabase: 1.215.0
- Version of Node.js: 20.15.0

## Additional context
I tried updating the storage-api version from 1.11.14 to 1.12.2 but the issue persists.

**Comment by avallete** [comment]
I confirm that I can reproduce on my end. Thank's for bringing this to our attention, will report back.

**Comment by ivasilov** [comment]
This has been fixed in the latest release in CLI. Please let us know if you're still seeing the issue.

**Comment by Wizzel1** [comment]
It is fixed, thanks
