### ISSUE TITLE
An OPTIONS request to the TUS URL does not contain the Tus-Version header

### ISSUE THREAD

**Issue by jfeaver** [supabase/storage#586]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I send an OPTIONS request to the TUS endpoint then I don't get a `Tus-Version` header in the response.

The [TUS protocol](https://tus.io/protocols/resumable-upload#options) states that "a successful response ... MUST contain the `Tus-Version` header".

## To Reproduce

1. Run a Supabase stack locally with Supabase Storage. Set up Kong on port 8000
2. Run this command line command:
```
curl -D - --request OPTIONS --url http://localhost:8000/storage/v1/upload/resumable
```

## Expected behavior

A `Tus-Version` header should be in the response headers.

I see this:
```
HTTP/1.1 204 No Content
Connection: keep-alive
Tus-Resumable: 1.0.0
Access-Control-Expose-Headers: Authorization, Content-Type, Location, Tus-Extension, Tus-Max-Size, Tus-Resumable, Tus-Version, Upload-Concat, Upload-Defer-Length, Upload-Length, Upload-Metadata, Upload-Offset, X-HTTP-Method-Override, X-Requested-With, X-Forwarded-Host, X-Forwarded-Proto, Forwarded, Upload-Expires
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, HEAD, PATCH, OPTIONS, DELETE
Access-Control-Allow-Headers: Authorization, Content-Type, Location, Tus-Extension, Tus-Max-Size, Tus-Resumable, Tus-Version, Upload-Concat, Upload-Defer-Length, Upload-Length, Upload-Metadata, Upload-Offset, X-HTTP-Method-Override, X-Requested-With, X-Forwarded-Host, X-Forwarded-Proto, Forwarded, Upload-Expires, X-Upsert, Upload-Expires, ApiKey
Access-Control-Max-Age: 86400
Tus-Extension: creation,creation-with-upload,creation-defer-length,termination,expiration
Tus-Max-Size: 1099511627776
Date: Thu, 14 Nov 2024 16:25:52 GMT
X-Kong-Upstream-Latency: 29
X-Kong-Proxy-Latency: 36
Via: kong/2.8.1
```

Docker image: supabase/studio:20230926-3e441e4

**Comment by fenos** [comment]
Hi @jfeaver thanks for reporting this.

I just checked this on the tus-node-server repo, and yes the Tus-Version seems to be missing from the OPTIONS request
Will follow up, upstream https://github.com/tus/tus-node-server/issues/674
