### ISSUE TITLE
Unable to delete `auth.users` row due to `objects_owner_fkey` FK constraint

### ISSUE THREAD

**Issue by liaujianjie** [supabase/storage#65]
# Bug report

## Describe the bug

When a user uploads an object to a bucket, the object's row in `storage.objects` has a column `owner` that has a FK constraint `objects_owner_fkey` to `auth.users.id`. However, it's not set up with `on delete {cascade|set null}`—which prevents the user from actually being deleted.

Attempting to delete a user with a `storage.object` referencing the user results in a FK constraint violation.

## To Reproduce

1. Create a user
2. Authenticate as that user on the client
3. Upload an object as that user on the client
4. Delete that user via dashboard
5. You'll get a FK constraint violation error:
   > Deleting user failed: update or delete on table "users" violates foreign key constraint "objects_owner_fkey" on table "objects"

## Expected behavior

Should be able to delete user whilst retaining the object in the database.

## Suggested fix & temporary workaround

Add `on delete set null` to the `objects_owner_fkey` constraint:

```sql
alter table storage.objects
drop constraint objects_owner_fkey,
add constraint objects_owner_fkey
   foreign key (owner)
   references auth.users(id)
   on delete set null;
```

**Comment by inian** [comment]
Thats a good point Jian. I will add a trigger to make the owner as null in storage.objects when a row is deleted from auth.users.

**Comment by mcewen87** [comment]
Hi @inian 

As I understand, the solution to this is to add this SQL

```alter table storage.objects
drop constraint objects_owner_fkey,
add constraint objects_owner_fkey
   foreign key (owner)
   references auth.users(id)
   on delete set null;```
   
   Is that correct?
   
   Additionally, can you share some insight into what is going on behind the scenes to create this restriction, and why it is in place?

**Comment by inian** [comment]
I haven't tested it out on an actual project but that does seem like it would work @mcewen87. The constraint is in place so that each storage owner is linked to an auth user and cos owner field shouldn't be any UUID.

**Comment by mcewen87** [comment]
> I haven't tested it out on an actual project but that does seem like it would work @mcewen87. The constraint is in place so that each storage owner is linked to an auth user and cos owner field shouldn't be any UUID.

Thank you! I'll give it a try.

**Comment by bennik88** [comment]
Did anyone figure out how to delete all the storage data for a user when the user is being deleted?
I tried it with a `BEFORE` `TRIGGER` and a function that would delete all storage objects before the user is being deleted but its still failing because of a foreign key constraint error.
```sql
create or replace function delete_all_storage_data_for_user()
returns trigger as
$$
  begin
    delete from storage.objects where bucket_id = 'user_storage' and (storage.foldername(name))[1] = auth.uid()::text;
    RETURN OLD;
  end;
$$
language plpgsql;
```

**Comment by theodufort** [comment]
On my side, I had a "users" table with constraint users_id_fkey between my stripe table and "auth.users" table.

I simply added :
`alter table users
drop constraint users_id_fkey,
add constraint users_id_fkey
   foreign key (id)
   references auth.users(id)
   on delete cascade;`

**Comment by fenos** [comment]
Feel free to re-open when providing more info

**Comment by tonyneel** [comment]
> Feel free to re-open when providing more info

Why would this need more info? You cannot delete a user from auth if they have records associated in the objects table. It is a bit of a pain.

**Comment by hansfuchs** [comment]
Faced the same issue today, didn't help that when I tried to delete a user through the UI (inside the Authentication tab), the error message was: "Failed to delete user: Failed to delete user". Only stumbled upon the actual error when I tried deleting the user through the SQL editor.

**Comment by mobile-development-group-com** [comment]
An example of this problem in production for us was when employees of a business updated image content within the application. However, we did not realize that the authentication object associated with the employee would become bound to that image asset, making it impossible to delete the authentication user afterwards. Although we were able to work around this issue, it would be helpful to have more control over this relationship when uploading assets, especially since we updated some signup logic.

**Comment by convcha** [comment]
workaround:  
Before deleting a user, delete all files using the supabase client.

```ts
const deleteAllUsers = async () => {
  const {
    data: { users },
  } = await client.auth.admin.listUsers();
  for (let user of users) {
    const directory = `users/${user.id}`;
    const fileRes = await client.storage.from("images").list(directory);
    for (let file of fileRes?.data ?? []) {
      console.log({ file });
      await client.storage.from("images").remove([`${directory}/${file.name}`]);
    }

    const { error } = await client.auth.admin.deleteUser(user.id);
    if (error) {
      console.log(`client.auth.admin.deleteUser(${user.id}) failed.`, {
        error,
      });
      throw new Error(error.message);
    }
  }
};
```

**Comment by kazuooooo** [comment]
In my case, I want to delete all objects(photos uploaded by a user) when the user is deleted.
So I fixed storage.objects table's owner column Cascade.

![1](https://github.com/supabase/storage-api/assets/6919381/e0da8854-b2eb-4d9a-bab2-f4e9e0fe75bf)
![2](https://github.com/supabase/storage-api/assets/6919381/defc9fe7-ba06-4992-b3ce-2d92a4bd7b70)

Now, user and objects can be deleted without error.

**Comment by inian** [comment]
We have removed the FK constraint now and we have a new column called `owner_id` and `owner` column is deprecated

**Comment by planasmultimedia** [comment]
Now you cannot edit the buckets table ... Don't know how to delete a user from the Auth :( I wanted to retry the Auth flow :(
